
version: 1.0.{build}

branches:

  only:

  - dev

build_script:

- sh: >-

    pacman -S git



    pacman -S mingw64/mingw-w64-x86_64-glfw



    pacman -S mingw64/mingw-w64-x86_64-freeglut



    mingw32-make.exe

