environment:
  matrix:

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu

  - job_name: OSX build
    appveyor_build_worker_image: macOS

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

matrix:
  fast_finish: true

init:
  - appveyor version

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows build

    environment:
      MSYSTEM: MINGW64
      MSYS_BASH: C:\msys64\usr\bin\bash
      CHERE_INVOKING: 1 # Tell msys2 to inherit the current directory when starting the shell

    build_script:
    - set OLD_PATH=%PATH%
    - set OPT_PATH=C:\msys64\mingw32\bin;C:\msys64\mingw64\bin;
    - set PATH=%OPT_PATH%%PATH%
    - set PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig;
    - '%MSYS_BASH% -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-glfw mingw64/mingw-w64-x86_64-freeglut"'
    - cd C:\projects\ncpilot
    - '%MSYS_BASH% -lc "mingw32-make.exe"'
    - 7z a ncPilot.zip C:\msys64\mingw64\bin\glfw3.dll
    - 7z a ncPilot.zip bin\release\ncPilot.exe
    - appveyor PushArtifact ncPilot.zip

  -
    matrix:
      only:
        - job_name: Linux build

    build_script:
    - sh: cd ~/projects/ncpilot
    - sh: sudo apt-get -y install libglfw3-dev mesa-common-dev libglu1-mesa-dev freeglut3-dev
    - sh: make


  -
    matrix:
      only:
        - job_name: OSX build

    build_script:
    - sh: cd ~/projects/ncpilot
    - sh: brew install glfw
    - sh: make
