version: 1.0.{build}

branches:

  only:

  - dev

environment:
  global:
    MSYS_BASH: C:\msys64\usr\bin\bash

build_script:

- '%MSYS_BASH% -lc "cd /c/projects/ncpilot; pacman --noconfirm -S mingw64/mingw-w64-x86_64-glfw mingw64/mingw-w64-x86_64-freeglut"'
- '%MSYS_BASH% -lc "PATH=$PATH:/mingw64/bin/"'
- '%MSYS_BASH% -lc "cd /c/projects/ncpilot; mingw32-make.exe"'