version: 1.0.{build}

branches:

  only:

  - dev

environment:
  global:
    MSYS_BASH: C:\msys64\bin\bash
    APPVEYOR_BUILD_FOLDER: C:\projects\ncpilot

build_script:

- '%MSYS_BASH% -l "cd $APPVEYOR_BUILD_FOLDER; pacman -S mingw64/mingw-w64-x86_64-glfw mingw64/mingw-w64-x86_64-freeglut"'
- '%MSYS_BASH% -l "cd $APPVEYOR_BUILD_FOLDER; mingw32-make.exe"'